import axios from 'axios';
import Groq from 'groq-sdk';
import nodemailer from 'nodemailer';
import PDFDocument from 'pdfkit';
import fs from 'fs';

const CONFIG = {
    API_KEY: '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',
    RECIPIENT: 'zohrab.rza@gmail.com',
    EMAIL_PASS: process.env.EMAIL_PASS,
    IDENTITY: "OpenClew AI Executive Strategist v4.0",
    SOURCES: [
        'https://deepmind.google/blog/rss.xml',
        'https://openai.com/news/rss.xml',
        'https://www.technologyreview.com/feed/',
        'https://hai.stanford.edu/news/rss.xml',
        'https://techcrunch.com/category/artificial-intelligence/feed/'
    ]
};

const groq = new Groq({ apiKey: CONFIG.API_KEY });

async function getIntelligence() {
    const url = CONFIG.SOURCES[Math.floor(Math.random() * CONFIG.SOURCES.length)];
    const res = await axios.get(url);
    const entries = res.data.split('<item>').slice(1, 4);
    
    return entries.map(e => ({
        title: (e.match(/<title>(?:<!\[CDATA\[)?([\s\S]*?)(?:]]>)?<\/title>/) || ["","N/A"])[1].trim(),
        link: (e.match(/<link>(?:<!\[CDATA\[)?([\s\S]*?)(?:]]>)?<\/link>/) || ["","#"])[1].trim()
    }));
}

async function analyze(news) {
    const prompt = `Sən Azərbaycanın ən qabaqcıl rəqəmsal transformasiya ekspertisən. 
    Bu xəbəri təhlil et: "${news.title}"
    
    Tələblər:
    - Dil: Müasir Azərbaycan işgüzar dili (Arxaik sözlərdən qaç).
    - Struktur:
      1. Qlobal Trend: Bu texnologiya dünyanı hara aparır?
      2. Yerli Tətbiq: Azərbaycanda hansı real layihəyə (məs. rəqəmsal hökumət, fintech) inteqrasiya oluna bilər?
      3. Strateji Addım: Qərar qəbul edən şəxslər sabah nə etməlidir?
    
    QEYD: "ə, ö, ğ, ç, ş, ı, İ" hərflərindən qüsursuz istifadə et. Mətni çox uzatma, konkret və "vuruşu" olan cümlələr qur.`;

    const response = await groq.chat.completions.create({
        messages: [{ role: 'user', content: prompt }],
        model: 'llama-3.3-70b-versatile',
        temperature: 0.3 // Daha ciddi və fokuslanmış cavab üçün
    });
    return response.choices[0].message.content;
}

async function createProfessionalPDF(data) {
    return new Promise((resolve) => {
        const doc = new PDFDocument({ margin: 40, size: 'A4' });
        const path = 'OpenClew_Intelligence.pdf';
        const stream = fs.createWriteStream(path);
        doc.pipe(stream);

        // Header Design
        doc.rect(0, 0, 612, 80).fill('#001F3F'); // Dark Navy Style
        doc.fillColor('#FFFFFF').fontSize(20).font('Helvetica-Bold').text('STRATEJİ ANALİTİK HESABAT', 40, 30);
        doc.fontSize(10).font('Helvetica').text(`Generated by ${CONFIG.IDENTITY}`, 40, 55);
        
        doc.moveDown(4);

        data.forEach((item, i) => {
            // Title (Hərfləri artıq "təmizləmirik", olduğu kimi saxlayırıq)
            doc.fillColor('#001F3F').fontSize(14).font('Helvetica-Bold').text(`${i+1}. ${item.title}`);
            doc.fontSize(8).fillColor('#888888').text(`URL: ${item.link}`);
            doc.moveDown(0.5);
            
            // Analiz mətni
            doc.fillColor('#333333').fontSize(11).font('Helvetica').text(item.analysis, {
                align: 'justify',
                lineGap: 3
            });
            
            doc.moveDown(2);
            doc.moveTo(40, doc.y).lineTo(550, doc.y).strokeColor('#EEEEEE').stroke();
            doc.moveDown(1.5);
        });

        doc.fontSize(8).fillColor('#AAAAAA').text('Məxfi sənəd - MDDT daxili istifadə üçün nəzərdə tutulmuşdur.', 40, 780, { align: 'center' });
        doc.end();
        stream.on('finish', () => resolve(path));
    });
}

async function main() {
    console.log("🚀 Agent Cycle Starting...");
    try {
        const news = await getIntelligence();
        const results = [];
        for (const n of news) {
            console.log(`🧠 Analyzing: ${n.title}`);
            const analysis = await analyze(n);
            results.push({ ...n, analysis });
        }
        
        const pdf = await createProfessionalPDF(results);
        
        let transporter = nodemailer.createTransport({
            service: 'gmail',
            auth: { user: CONFIG.RECIPIENT, pass: CONFIG.EMAIL_PASS }
        });

        await transporter.sendMail({
            from: `"OpenClew AI" <${CONFIG.RECIPIENT}>`,
            to: CONFIG.RECIPIENT,
            subject: `🚀 STRATEJİ İNSAYT: ${new Date().toLocaleDateString('az-AZ')}`,
            text: `Zöhrab bəy, günün rəqəmsal kəşfiyyat analizi əlavədədir.`,
            attachments: [{ filename: 'Strategic_Report.pdf', path: pdf }]
        });
        console.log("🏁 Cycle Complete.");
    } catch (err) {
        console.error(err);
        process.exit(1);
    }
}

main();
